openapi: 3.0.0
info:
  version: '2017-11-27'
  x-release: v4
  title: 'Amazon Comprehend #X Amz Target=Comprehend 20171127.BatchDetectDominantLanguage #X Amz Target=Comprehend 20171127.BatchDetectDominantLanguage #X Amz Target=Comprehend 20171127.BatchDetectTargetedSentiment API'
  description: Amazon Comprehend is an Amazon Web Services service for gaining insight into the content of documents. Use these actions to determine the topics contained in your documents, the topics they discuss, the predominant sentiment expressed in them, the predominant language used, and more.
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: comprehend
  x-aws-signingName: comprehend
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/comprehend-2017-11-27.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://comprehend.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon Comprehend multi-region endpoint
- url: https://comprehend.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon Comprehend multi-region endpoint
- url: http://comprehend.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon Comprehend endpoint for China (Beijing) and China (Ningxia)
- url: https://comprehend.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon Comprehend endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=Comprehend 20171127.BatchDetectTargetedSentiment'
paths:
  /#X-Amz-Target=Comprehend_20171127.BatchDetectTargetedSentiment:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: BatchDetectTargetedSentiment
      description: <p>Inspects a batch of documents and returns a sentiment analysis for each entity identified in the documents.</p> <p>For more information about targeted sentiment, see <a href="https://docs.aws.amazon.com/comprehend/latest/dg/how-targeted-sentiment.html">Targeted sentiment</a>.</p>
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchDetectTargetedSentimentResponse'
              examples:
                BatchDetectTargetedSentiment200Example:
                  summary: Default BatchDetectTargetedSentiment 200
                  x-microcks-default: true
                  value:
                    ResultList: example
                    ErrorList: example
        '480':
          description: InvalidRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestException'
              examples:
                BatchDetectTargetedSentiment480Example:
                  summary: Default BatchDetectTargetedSentiment 480
                  x-microcks-default: true
                  value: example
        '481':
          description: TextSizeLimitExceededException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TextSizeLimitExceededException'
              examples:
                BatchDetectTargetedSentiment481Example:
                  summary: Default BatchDetectTargetedSentiment 481
                  x-microcks-default: true
                  value: example
        '482':
          description: UnsupportedLanguageException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnsupportedLanguageException'
              examples:
                BatchDetectTargetedSentiment482Example:
                  summary: Default BatchDetectTargetedSentiment 482
                  x-microcks-default: true
                  value: example
        '483':
          description: BatchSizeLimitExceededException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchSizeLimitExceededException'
              examples:
                BatchDetectTargetedSentiment483Example:
                  summary: Default BatchDetectTargetedSentiment 483
                  x-microcks-default: true
                  value: example
        '484':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
              examples:
                BatchDetectTargetedSentiment484Example:
                  summary: Default BatchDetectTargetedSentiment 484
                  x-microcks-default: true
                  value: example
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchDetectTargetedSentimentRequest'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - Comprehend_20171127.BatchDetectTargetedSentiment
      summary: Amazon Comprehend Batch Detect Targeted Sentiment
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=Comprehend 20171127.BatchDetectTargetedSentiment'
components:
  schemas:
    LanguageCode:
      type: string
      enum:
      - en
      - es
      - fr
      - de
      - it
      - pt
      - ar
      - hi
      - ja
      - ko
      - zh
      - zh-TW
    BatchSizeLimitExceededException: {}
    UnsupportedLanguageException: {}
    TargetedSentimentEntityType:
      type: string
      enum:
      - PERSON
      - LOCATION
      - ORGANIZATION
      - FACILITY
      - BRAND
      - COMMERCIAL_ITEM
      - MOVIE
      - MUSIC
      - BOOK
      - SOFTWARE
      - GAME
      - PERSONAL_TITLE
      - EVENT
      - DATE
      - QUANTITY
      - ATTRIBUTE
      - OTHER
    SentimentType:
      type: string
      enum:
      - POSITIVE
      - NEGATIVE
      - NEUTRAL
      - MIXED
    TextSizeLimitExceededException: {}
    BatchDetectTargetedSentimentRequest:
      type: object
      required:
      - TextList
      - LanguageCode
      title: BatchDetectTargetedSentimentRequest
      properties:
        TextList:
          allOf:
          - $ref: '#/components/schemas/CustomerInputStringList'
          - description: A list containing the UTF-8 encoded text of the input documents. The list can contain a maximum of 25 documents. The maximum size of each document is 5 KB.
        LanguageCode:
          allOf:
          - $ref: '#/components/schemas/LanguageCode'
          - description: The language of the input documents. Currently, English is the only supported language.
    TargetedSentimentEntity:
      type: object
      properties:
        DescriptiveMentionIndex:
          allOf:
          - $ref: '#/components/schemas/ListOfDescriptiveMentionIndices'
          - description: One or more index into the Mentions array that provides the best name for the entity group.
        Mentions:
          allOf:
          - $ref: '#/components/schemas/ListOfMentions'
          - description: 'An array of mentions of the entity in the document. The array represents a co-reference group. See <a href="https://docs.aws.amazon.com/comprehend/latest/dg/how-targeted-sentiment.html#how-targeted-sentiment-values"> Co-reference group</a> for an example. '
      description: <p>Information about one of the entities found by targeted sentiment analysis.</p> <p>For more information about targeted sentiment, see <a href="https://docs.aws.amazon.com/comprehend/latest/dg/how-targeted-sentiment.html">Targeted sentiment</a>.</p>
    ListOfMentions:
      type: array
      items:
        $ref: '#/components/schemas/TargetedSentimentMention'
    SentimentScore:
      type: object
      properties:
        Positive:
          allOf:
          - $ref: '#/components/schemas/Float'
          - description: The level of confidence that Amazon Comprehend has in the accuracy of its detection of the <code>POSITIVE</code> sentiment.
        Negative:
          allOf:
          - $ref: '#/components/schemas/Float'
          - description: The level of confidence that Amazon Comprehend has in the accuracy of its detection of the <code>NEGATIVE</code> sentiment.
        Neutral:
          allOf:
          - $ref: '#/components/schemas/Float'
          - description: The level of confidence that Amazon Comprehend has in the accuracy of its detection of the <code>NEUTRAL</code> sentiment.
        Mixed:
          allOf:
          - $ref: '#/components/schemas/Float'
          - description: The level of confidence that Amazon Comprehend has in the accuracy of its detection of the <code>MIXED</code> sentiment.
      description: Describes the level of confidence that Amazon Comprehend has in the accuracy of its detection of sentiments.
    BatchDetectTargetedSentimentItemResult:
      type: object
      properties:
        Index:
          allOf:
          - $ref: '#/components/schemas/Integer'
          - description: The zero-based index of this result in the input list.
        Entities:
          allOf:
          - $ref: '#/components/schemas/ListOfTargetedSentimentEntities'
          - description: An array of targeted sentiment entities.
      description: Analysis results for one of the documents in the batch.
    ListOfDetectTargetedSentimentResult:
      type: array
      items:
        $ref: '#/components/schemas/BatchDetectTargetedSentimentItemResult'
    InvalidRequestException: {}
    MentionSentiment:
      type: object
      properties:
        Sentiment:
          allOf:
          - $ref: '#/components/schemas/SentimentType'
          - description: 'The sentiment of the mention. '
        SentimentScore:
          $ref: '#/components/schemas/SentimentScore'
      description: <p>Contains the sentiment and sentiment score for one mention of an entity.</p> <p>For more information about targeted sentiment, see <a href="https://docs.aws.amazon.com/comprehend/latest/dg/how-targeted-sentiment.html">Targeted sentiment</a>.</p>
    Float:
      type: number
      format: float
    TargetedSentimentMention:
      type: object
      properties:
        Score:
          allOf:
          - $ref: '#/components/schemas/Float'
          - description: Model confidence that the entity is relevant. Value range is zero to one, where one is highest confidence.
        GroupScore:
          allOf:
          - $ref: '#/components/schemas/Float'
          - description: The confidence that all the entities mentioned in the group relate to the same entity.
        Text:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The text in the document that identifies the entity.
        Type:
          allOf:
          - $ref: '#/components/schemas/TargetedSentimentEntityType'
          - description: The type of the entity. Amazon Comprehend supports a variety of <a href="https://docs.aws.amazon.com/comprehend/latest/dg/how-targeted-sentiment.html#how-targeted-sentiment-entities">entity types</a>.
        MentionSentiment:
          allOf:
          - $ref: '#/components/schemas/MentionSentiment'
          - description: Contains the sentiment and sentiment score for the mention.
        BeginOffset:
          allOf:
          - $ref: '#/components/schemas/Integer'
          - description: The offset into the document text where the mention begins.
        EndOffset:
          allOf:
          - $ref: '#/components/schemas/Integer'
          - description: The offset into the document text where the mention ends.
      description: <p>Information about one mention of an entity. The mention information includes the location of the mention in the text and the sentiment of the mention.</p> <p>For more information about targeted sentiment, see <a href="https://docs.aws.amazon.com/comprehend/latest/dg/how-targeted-sentiment.html">Targeted sentiment</a>.</p>
    String:
      type: string
      minLength: 1
    CustomerInputStringList:
      type: array
      items:
        $ref: '#/components/schemas/CustomerInputString'
      minItems: 1
    BatchItemErrorList:
      type: array
      items:
        $ref: '#/components/schemas/BatchItemError'
    Integer:
      type: integer
    ListOfDescriptiveMentionIndices:
      type: array
      items:
        $ref: '#/components/schemas/Integer'
    ListOfTargetedSentimentEntities:
      type: array
      items:
        $ref: '#/components/schemas/TargetedSentimentEntity'
    CustomerInputString:
      type: string
      minLength: 1
      format: password
    BatchDetectTargetedSentimentResponse:
      type: object
      required:
      - ResultList
      - ErrorList
      properties:
        ResultList:
          allOf:
          - $ref: '#/components/schemas/ListOfDetectTargetedSentimentResult'
          - description: A list of objects containing the results of the operation. The results are sorted in ascending order by the <code>Index</code> field and match the order of the documents in the input list. If all of the documents contain an error, the <code>ResultList</code> is empty.
        ErrorList:
          allOf:
          - $ref: '#/components/schemas/BatchItemErrorList'
          - description: List of errors that the operation can return.
    BatchItemError:
      type: object
      properties:
        Index:
          allOf:
          - $ref: '#/components/schemas/Integer'
          - description: The zero-based index of the document in the input list.
        ErrorCode:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The numeric error code of the error.
        ErrorMessage:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: A text description of the error.
      description: Describes an error that occurred while processing a document in a batch. The operation returns on <code>BatchItemError</code> object for each document that contained an error.
    InternalServerException: {}
  parameters:
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/comprehend/
x-hasEquivalentPaths: true
