openapi: 3.0.0
info:
  version: '2017-11-27'
  x-release: v4
  title: 'Amazon Comprehend #X Amz Target=Comprehend 20171127.BatchDetectDominantLanguage #X Amz Target=Comprehend 20171127.BatchDetectDominantLanguage #X Amz Target=Comprehend 20171127.DetectSentiment API'
  description: Amazon Comprehend is an Amazon Web Services service for gaining insight into the content of documents. Use these actions to determine the topics contained in your documents, the topics they discuss, the predominant sentiment expressed in them, the predominant language used, and more.
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: comprehend
  x-aws-signingName: comprehend
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/comprehend-2017-11-27.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://comprehend.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon Comprehend multi-region endpoint
- url: https://comprehend.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon Comprehend multi-region endpoint
- url: http://comprehend.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon Comprehend endpoint for China (Beijing) and China (Ningxia)
- url: https://comprehend.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon Comprehend endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=Comprehend 20171127.DetectSentiment'
paths:
  /#X-Amz-Target=Comprehend_20171127.DetectSentiment:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: DetectSentiment
      description: 'Inspects text and returns an inference of the prevailing sentiment (<code>POSITIVE</code>, <code>NEUTRAL</code>, <code>MIXED</code>, or <code>NEGATIVE</code>). '
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetectSentimentResponse'
              examples:
                DetectSentiment200Example:
                  summary: Default DetectSentiment 200
                  x-microcks-default: true
                  value:
                    Sentiment: example
                    SentimentScore: example
        '480':
          description: InvalidRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestException'
              examples:
                DetectSentiment480Example:
                  summary: Default DetectSentiment 480
                  x-microcks-default: true
                  value: example
        '481':
          description: TextSizeLimitExceededException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TextSizeLimitExceededException'
              examples:
                DetectSentiment481Example:
                  summary: Default DetectSentiment 481
                  x-microcks-default: true
                  value: example
        '482':
          description: UnsupportedLanguageException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnsupportedLanguageException'
              examples:
                DetectSentiment482Example:
                  summary: Default DetectSentiment 482
                  x-microcks-default: true
                  value: example
        '483':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
              examples:
                DetectSentiment483Example:
                  summary: Default DetectSentiment 483
                  x-microcks-default: true
                  value: example
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DetectSentimentRequest'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - Comprehend_20171127.DetectSentiment
      summary: Amazon Comprehend Detect Sentiment
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=Comprehend 20171127.DetectSentiment'
components:
  schemas:
    LanguageCode:
      type: string
      enum:
      - en
      - es
      - fr
      - de
      - it
      - pt
      - ar
      - hi
      - ja
      - ko
      - zh
      - zh-TW
    InvalidRequestException: {}
    UnsupportedLanguageException: {}
    Float:
      type: number
      format: float
    SentimentScore:
      type: object
      properties:
        Positive:
          allOf:
          - $ref: '#/components/schemas/Float'
          - description: The level of confidence that Amazon Comprehend has in the accuracy of its detection of the <code>POSITIVE</code> sentiment.
        Negative:
          allOf:
          - $ref: '#/components/schemas/Float'
          - description: The level of confidence that Amazon Comprehend has in the accuracy of its detection of the <code>NEGATIVE</code> sentiment.
        Neutral:
          allOf:
          - $ref: '#/components/schemas/Float'
          - description: The level of confidence that Amazon Comprehend has in the accuracy of its detection of the <code>NEUTRAL</code> sentiment.
        Mixed:
          allOf:
          - $ref: '#/components/schemas/Float'
          - description: The level of confidence that Amazon Comprehend has in the accuracy of its detection of the <code>MIXED</code> sentiment.
      description: Describes the level of confidence that Amazon Comprehend has in the accuracy of its detection of sentiments.
    CustomerInputString:
      type: string
      minLength: 1
      format: password
    InternalServerException: {}
    SentimentType:
      type: string
      enum:
      - POSITIVE
      - NEGATIVE
      - NEUTRAL
      - MIXED
    TextSizeLimitExceededException: {}
    DetectSentimentResponse:
      type: object
      properties:
        Sentiment:
          allOf:
          - $ref: '#/components/schemas/SentimentType'
          - description: The inferred sentiment that Amazon Comprehend has the highest level of confidence in.
        SentimentScore:
          allOf:
          - $ref: '#/components/schemas/SentimentScore'
          - description: An object that lists the sentiments, and their corresponding confidence levels.
    DetectSentimentRequest:
      type: object
      required:
      - Text
      - LanguageCode
      title: DetectSentimentRequest
      properties:
        Text:
          allOf:
          - $ref: '#/components/schemas/CustomerInputString'
          - description: A UTF-8 text string. The maximum string size is 5 KB.
        LanguageCode:
          allOf:
          - $ref: '#/components/schemas/LanguageCode'
          - description: The language of the input documents. You can specify any of the primary languages supported by Amazon Comprehend. All documents must be in the same language.
  parameters:
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/comprehend/
x-hasEquivalentPaths: true
