openapi: 3.0.0
info:
  version: '2017-11-27'
  x-release: v4
  title: 'Amazon Comprehend #X Amz Target=Comprehend 20171127.BatchDetectDominantLanguage #X Amz Target=Comprehend 20171127.BatchDetectDominantLanguage #X Amz Target=Comprehend 20171127.BatchDetectDominantLanguage API'
  description: Amazon Comprehend is an Amazon Web Services service for gaining insight into the content of documents. Use these actions to determine the topics contained in your documents, the topics they discuss, the predominant sentiment expressed in them, the predominant language used, and more.
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: comprehend
  x-aws-signingName: comprehend
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/comprehend-2017-11-27.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://comprehend.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon Comprehend multi-region endpoint
- url: https://comprehend.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon Comprehend multi-region endpoint
- url: http://comprehend.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon Comprehend endpoint for China (Beijing) and China (Ningxia)
- url: https://comprehend.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon Comprehend endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=Comprehend 20171127.BatchDetectDominantLanguage'
paths:
  /#X-Amz-Target=Comprehend_20171127.BatchDetectDominantLanguage:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: BatchDetectDominantLanguage
      description: 'Determines the dominant language of the input text for a batch of documents. For a list of languages that Amazon Comprehend can detect, see <a href="https://docs.aws.amazon.com/comprehend/latest/dg/how-languages.html">Amazon Comprehend Supported Languages</a>. '
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchDetectDominantLanguageResponse'
              examples:
                BatchDetectDominantLanguage200Example:
                  summary: Default BatchDetectDominantLanguage 200
                  x-microcks-default: true
                  value:
                    ResultList: example
                    ErrorList: example
        '480':
          description: InvalidRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestException'
              examples:
                BatchDetectDominantLanguage480Example:
                  summary: Default BatchDetectDominantLanguage 480
                  x-microcks-default: true
                  value: example
        '481':
          description: TextSizeLimitExceededException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TextSizeLimitExceededException'
              examples:
                BatchDetectDominantLanguage481Example:
                  summary: Default BatchDetectDominantLanguage 481
                  x-microcks-default: true
                  value: example
        '482':
          description: BatchSizeLimitExceededException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchSizeLimitExceededException'
              examples:
                BatchDetectDominantLanguage482Example:
                  summary: Default BatchDetectDominantLanguage 482
                  x-microcks-default: true
                  value: example
        '483':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
              examples:
                BatchDetectDominantLanguage483Example:
                  summary: Default BatchDetectDominantLanguage 483
                  x-microcks-default: true
                  value: example
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchDetectDominantLanguageRequest'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - Comprehend_20171127.BatchDetectDominantLanguage
      summary: Amazon Comprehend Batch Detect Dominant Language
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=Comprehend 20171127.BatchDetectDominantLanguage'
components:
  schemas:
    BatchSizeLimitExceededException: {}
    BatchDetectDominantLanguageRequest:
      type: object
      required:
      - TextList
      title: BatchDetectDominantLanguageRequest
      properties:
        TextList:
          allOf:
          - $ref: '#/components/schemas/CustomerInputStringList'
          - description: A list containing the UTF-8 encoded text of the input documents. The list can contain a maximum of 25 documents. Each document should contain at least 20 characters. The maximum size of each document is 5 KB.
    ListOfDominantLanguages:
      type: array
      items:
        $ref: '#/components/schemas/DominantLanguage'
    TextSizeLimitExceededException: {}
    DominantLanguage:
      type: object
      properties:
        LanguageCode:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The RFC 5646 language code for the dominant language. For more information about RFC 5646, see <a href="https://tools.ietf.org/html/rfc5646">Tags for Identifying Languages</a> on the <i>IETF Tools</i> web site.
        Score:
          allOf:
          - $ref: '#/components/schemas/Float'
          - description: The level of confidence that Amazon Comprehend has in the accuracy of the detection.
      description: Returns the code for the dominant language in the input text and the level of confidence that Amazon Comprehend has in the accuracy of the detection.
    BatchDetectDominantLanguageItemResult:
      type: object
      properties:
        Index:
          allOf:
          - $ref: '#/components/schemas/Integer'
          - description: The zero-based index of the document in the input list.
        Languages:
          allOf:
          - $ref: '#/components/schemas/ListOfDominantLanguages'
          - description: One or more <a>DominantLanguage</a> objects describing the dominant languages in the document.
      description: The result of calling the operation. The operation returns one object for each document that is successfully processed by the operation.
    BatchDetectDominantLanguageResponse:
      type: object
      required:
      - ResultList
      - ErrorList
      properties:
        ResultList:
          allOf:
          - $ref: '#/components/schemas/ListOfDetectDominantLanguageResult'
          - description: A list of objects containing the results of the operation. The results are sorted in ascending order by the <code>Index</code> field and match the order of the documents in the input list. If all of the documents contain an error, the <code>ResultList</code> is empty.
        ErrorList:
          allOf:
          - $ref: '#/components/schemas/BatchItemErrorList'
          - description: A list containing one object for each document that contained an error. The results are sorted in ascending order by the <code>Index</code> field and match the order of the documents in the input list. If there are no errors in the batch, the <code>ErrorList</code> is empty.
    ListOfDetectDominantLanguageResult:
      type: array
      items:
        $ref: '#/components/schemas/BatchDetectDominantLanguageItemResult'
    InvalidRequestException: {}
    Float:
      type: number
      format: float
    String:
      type: string
      minLength: 1
    CustomerInputStringList:
      type: array
      items:
        $ref: '#/components/schemas/CustomerInputString'
      minItems: 1
    BatchItemErrorList:
      type: array
      items:
        $ref: '#/components/schemas/BatchItemError'
    Integer:
      type: integer
    CustomerInputString:
      type: string
      minLength: 1
      format: password
    BatchItemError:
      type: object
      properties:
        Index:
          allOf:
          - $ref: '#/components/schemas/Integer'
          - description: The zero-based index of the document in the input list.
        ErrorCode:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The numeric error code of the error.
        ErrorMessage:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: A text description of the error.
      description: Describes an error that occurred while processing a document in a batch. The operation returns on <code>BatchItemError</code> object for each document that contained an error.
    InternalServerException: {}
  parameters:
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/comprehend/
x-hasEquivalentPaths: true
